repos:
  # Frontend hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  # TypeScript and React hooks
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bash -c 'cd apps/web && npm run lint'
        language: system
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: false
        
      - id: typescript-check
        name: TypeScript Check
        entry: bash -c 'cd apps/web && npx tsc --noEmit'
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

  # Python/FastAPI hooks
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        files: ^apps/api/
        
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^apps/api/
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # Prevent committing to main
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]